Importing advisory data from 'adv.list.json'
/home/dim/workspace/git/gitblit/cve-tracker/.venv/lib/python3.5/site-packages/sqlalchemy/orm/relationships.py:1424: SAWarning: Got None for value of column advisory.id; this is unsupported for a relationship comparison and will not currently produce an IS comparison (but may in a future release)
  "(but may in a future release)" % column)
Import done. Imported 200 advisory object(s).
